[package]
name = "ewt"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[lib]
crate-type = ["cdylib"]

[dependencies]
bindgen = "0.71.1"
# emacs = "0.11.0"
icu_segmenter = "1.5.0"
libc = "0.2.169"
windows = { version = "0.58.0", features = [
    "Data_Text",
    "Foundation_Collections",
] }

[build-dependencies]
bindgen = "0.71.1"
