[package]
name = "ewt"
version = "0.2.0"
edition = "2021"
license = "GPL-3.0-or-later"

[lib]
crate-type = ["cdylib"]

[dependencies]
icu_segmenter = { version = "1.5.0", optional = true }
libc = "0.2.169"
windows = { version = "0.58.0", features = [
    "Data_Text",
    "Foundation_Collections",
], optional = true }
itertools = { version = "0.13.0", optional = true }

[build-dependencies]
bindgen = "0.71.1"

[profile.release]
codegen-units = 1
lto = true
strip = true
panic = "abort"

[features]
default = ["icu_segmenter"]
# default = ["windows"]
icu_segmenter = ["dep:icu_segmenter", "dep:itertools"]
